version: '3.3'
services:
  app:
    build:
      context: .
    command: tail -F anything
    volumes:
      - ./:/home:delegated
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"